# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-10 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avechi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.IntegerField(default=0)),
                ('product_warranty', models.CharField(max_length=200)),
                ('product_discount', models.IntegerField(blank=True, default=0, null=True)),
                ('product_seller', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('return_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jumia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.IntegerField(default=0)),
                ('product_warranty', models.CharField(max_length=200)),
                ('product_discount', models.IntegerField(blank=True, default=0, null=True)),
                ('product_seller', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('return_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Killmall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.IntegerField(default=0)),
                ('product_warranty', models.CharField(max_length=200)),
                ('product_discount', models.IntegerField(blank=True, default=0, null=True)),
                ('product_seller', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('return_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=1000)),
                ('product_image', models.CharField(max_length=10000)),
                ('product_rating', models.IntegerField(blank=True, default=0, null=True)),
                ('product_key_features', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='killmall',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kenyan_stores_scraper.Products'),
        ),
        migrations.AddField(
            model_name='jumia',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kenyan_stores_scraper.Products'),
        ),
        migrations.AddField(
            model_name='avechi',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kenyan_stores_scraper.Products'),
        ),
    ]
